# Déclaration explicite du réseau
networks:
  healthcare-network:
    driver: bridge

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_healthcare
    env_file: .env
    networks:
      - healthcare-network
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    # Healthcheck pour valider le démarrage
    healthcheck:
      test: ["CMD-SHELL", "mongosh -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval \"db.adminCommand('ping')\" --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Service qui lance la migration puis les tests
  migration_and_tests:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: migration_script
    env_file: .env
    networks:
      - healthcare-network
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - .:/app
    # si la migration échoue, les tests ne se lancent pas
    command: sh -c "python migration.py && pytest test_migration.py -v"

volumes:
  mongo_data: {}